SELECT
    B.COLUMN_NAME,
    B.DATA_TYPE AS DATA_TYPE,
    NVL(B.DATA_PRECISION,B.DATA_LENGTH) AS DATA_LENGTH,
    B.NULLABLE AS NULLABLE,
    B.DATA_DEFAULT AS DATA_DEFAULT,
    B.DATA_SCALE AS DATA_SCALE,
    A.COMMENTS AS COMMENTS
FROM
    ALL_COL_COMMENTS A,
    ALL_TAB_COLUMNS B
WHERE
        1 = 1
  AND A.TABLE_NAME = B.TABLE_NAME
  AND A.COLUMN_NAME = B.COLUMN_NAME
  AND A.SCHEMA_NAME = ?
  AND B.OWNER = ?
  AND A.TABLE_NAME = ?
ORDER BY
    A.TABLE_NAME,
    B.COLUMN_ID