SELECT
    B.COLUMN_NAME,
    B.DATA_TYPE AS DATA_TYPE,
    NVL(B.DATA_PRECISION,
        B.DATA_LENGTH) AS DATA_LENGTH,
    B.NULLABLE AS NULLABLE,
    B.DATA_DEFAULT AS DATA_DEFAULT,
    B.DATA_SCALE AS DATA_SCALE,
    A.COMMENTS AS COMMENTS,
    CASE WHEN EXISTS (
        SELECT 1
        FROM USER_CONS_COLUMNS ucc
                 JOIN USER_CONSTRAINTS uc ON ucc.CONSTRAINT_NAME = uc.CONSTRAINT_NAME
        WHERE ucc.COLUMN_NAME = B.COLUMN_NAME
          AND ucc.TABLE_NAME = A.TABLE_NAME
          AND uc.CONSTRAINT_TYPE = 'P'
    ) THEN 'YES' ELSE 'NO' END AS IS_PRIMARY_KEY
FROM
    ALL_COL_COMMENTS A,
    ALL_TAB_COLUMNS B
WHERE
    1 = 1
  AND A.TABLE_NAME = B.TABLE_NAME
  AND A.COLUMN_NAME = B.COLUMN_NAME
  AND A.SCHEMA_NAME = '%s'
  AND B.OWNER = '%s'
  AND A.TABLE_NAME = '%s'
ORDER BY
    A.TABLE_NAME,
    B.COLUMN_ID