SELECT
    B.COLUMN_NAME,
    B.DATA_TYPE,
    B.DATA_LENGTH,
    B.DATA_PRECISION,
    B.DATA_SCALE,
    B.NULLABLE,
    B.DATA_DEFAULT,
    A.COMMENTS
FROM
    USER_COL_COMMENTS A,
    USER_TAB_COLUMNS B,
    USER_TAB_COMMENTS C
WHERE
    1 = 1
  AND A.TABLE_NAME IN ( SELECT U.TABLE_NAME FROM USER_ALL_TABLES U )
  AND A.TABLE_NAME = B.TABLE_NAME
  AND A.COLUMN_NAME = B.COLUMN_NAME
  AND C.TABLE_NAME = A.TABLE_NAME
  AND A.TABLE_NAME = '%s'
ORDER BY
    A.TABLE_NAME,
    B.COLUMN_ID